server:
  port: 8080

spring:
  application:
    name: analisis_impacto


  datasource:
    url: jdbc:mysql://localhost:3306/an_impacto?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true



# Configuración JWT
jwt:
  secret: tuClaveSecretaMuyLargaYSeguraParaFirmarTokensJWT2024
  expiration: 86400000  # 24 horas en ms